// Copyright 2020-2025 SIX AFTER, INC (SIX AFTER)
//
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: SIX AFTER, INC (SIX AFTER)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: country_subdivision.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The `CountrySubdivision` message represents a subdivision of a country,
// such as a state, province, or territory, as defined by the ISO-3166-2 standard.
// This is commonly used for addressing, geolocation, and administrative purposes.
type CountrySubdivision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the subdivision.
	// Example: "Texas".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The ISO 3166-2 code for the subdivision.
	// This is a code that uniquely identifies the subdivision within its country.
	// Example: "US-TX" for Texas in the United States.
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// The country to which this subdivision belongs.
	Country       *Country `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountrySubdivision) Reset() {
	*x = CountrySubdivision{}
	mi := &file_country_subdivision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountrySubdivision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountrySubdivision) ProtoMessage() {}

func (x *CountrySubdivision) ProtoReflect() protoreflect.Message {
	mi := &file_country_subdivision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountrySubdivision.ProtoReflect.Descriptor instead.
func (*CountrySubdivision) Descriptor() ([]byte, []int) {
	return file_country_subdivision_proto_rawDescGZIP(), []int{0}
}

func (x *CountrySubdivision) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CountrySubdivision) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CountrySubdivision) GetCountry() *Country {
	if x != nil {
		return x.Country
	}
	return nil
}

var File_country_subdivision_proto protoreflect.FileDescriptor

const file_country_subdivision_proto_rawDesc = "" +
	"\n" +
	"\x19country_subdivision.proto\x12\x0esixafter.types\x1a\rcountry.proto\"o\n" +
	"\x12CountrySubdivision\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x121\n" +
	"\acountry\x18\x03 \x01(\v2\x17.sixafter.types.CountryR\acountryBy\n" +
	"\x12com.sixafter.typesB\x17CountrySubdivisionProtoP\x01Z\x1fgithub.com/sixafter/types;types\xf8\x01\x01\xa2\x02\x03TPB\xaa\x02\x1dSixAfter.Types.WellKnownTypesb\x06proto3"

var (
	file_country_subdivision_proto_rawDescOnce sync.Once
	file_country_subdivision_proto_rawDescData []byte
)

func file_country_subdivision_proto_rawDescGZIP() []byte {
	file_country_subdivision_proto_rawDescOnce.Do(func() {
		file_country_subdivision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_country_subdivision_proto_rawDesc), len(file_country_subdivision_proto_rawDesc)))
	})
	return file_country_subdivision_proto_rawDescData
}

var file_country_subdivision_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_country_subdivision_proto_goTypes = []any{
	(*CountrySubdivision)(nil), // 0: sixafter.types.CountrySubdivision
	(*Country)(nil),            // 1: sixafter.types.Country
}
var file_country_subdivision_proto_depIdxs = []int32{
	1, // 0: sixafter.types.CountrySubdivision.country:type_name -> sixafter.types.Country
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_country_subdivision_proto_init() }
func file_country_subdivision_proto_init() {
	if File_country_subdivision_proto != nil {
		return
	}
	file_country_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_country_subdivision_proto_rawDesc), len(file_country_subdivision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_country_subdivision_proto_goTypes,
		DependencyIndexes: file_country_subdivision_proto_depIdxs,
		MessageInfos:      file_country_subdivision_proto_msgTypes,
	}.Build()
	File_country_subdivision_proto = out.File
	file_country_subdivision_proto_goTypes = nil
	file_country_subdivision_proto_depIdxs = nil
}
