// Copyright 2020-2024 SIX AFTER, INC (SIX AFTER)
//
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: SIX AFTER, INC (SIX AFTER)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: entity_metadata.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The `EntityMetadata` message represents metadata associated with an entity.
// This includes timestamps, versioning, and additional descriptive properties,
// providing a comprehensive overview of the entity's lifecycle and characteristics.
type EntityMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The timestamp at which the entity was created.
	// Example: "2024-11-17T12:34:56Z" for an entity created on November 17, 2024.
	CreatedOn *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	// The timestamp at which the entity was last modified.
	// Example: "2024-11-18T08:20:45Z" for an entity last updated on November 18, 2024.
	ModifiedOn *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=modified_on,json=modifiedOn,proto3" json:"modified_on,omitempty"`
	// The timestamp at which the entity was deleted, if applicable.
	// Example: "2024-11-19T15:00:00Z" for an entity marked as deleted on November 19, 2024.
	DeletedOn *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_on,json=deletedOn,proto3" json:"deleted_on,omitempty"`
	// Indicates whether the entity is ephemeral.
	// An ephemeral entity is temporary and may not be persisted or stored long-term.
	// Example: `true` for a session-based entity.
	Ephemeral bool `protobuf:"varint,4,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	// Indicates whether the entity can be replicated with external sources.
	// Example: `true` for an entity designed to synchronize with external systems.
	Replicable bool `protobuf:"varint,5,opt,name=replicable,proto3" json:"replicable,omitempty"`
	// Indicates whether the entity is immutable.
	// An immutable entity cannot be modified after creation.
	// Example: `true` for a cryptographic hash record.
	Immutable bool `protobuf:"varint,6,opt,name=immutable,proto3" json:"immutable,omitempty"`
	// The Semantic Version v2.0 compliant version of the entity.
	// This provides versioning information for tracking changes and compatibility.
	// Example: Version `1.0.0` for the initial release of the entity.
	Version *Version `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	// Indicates whether the entity was synthesized (or is synthetic).
	// A synthetic entity is derived or generated, rather than directly created by users.
	// Example: `true` for an entity generated by machine learning algorithms.
	Synthetic bool `protobuf:"varint,8,opt,name=synthetic,proto3" json:"synthetic,omitempty"`
	// A list of tags associated with the entity.
	// Tags provide descriptive labels for categorization or search.
	// Tags must have:
	// - A minimum length of 1 character
	// - A maximum length of 256 characters
	// - A pattern matching "^[a-zA-Z0-9_-]+$" (alphanumeric, underscores, and hyphens).
	// Example: `["finance", "report2024"]` for an entity tagged as a 2024 finance report.
	Tags []string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	// Custom attributes for additional metadata in key-value format.
	// The keys and values are strings, allowing flexible metadata descriptions.
	// Example: `{"source": "API", "priority": "high"}` for an entity from the API with high priority.
	Attributes    *structpb.Struct `protobuf:"bytes,10,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMetadata) Reset() {
	*x = EntityMetadata{}
	mi := &file_entity_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMetadata) ProtoMessage() {}

func (x *EntityMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_entity_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMetadata.ProtoReflect.Descriptor instead.
func (*EntityMetadata) Descriptor() ([]byte, []int) {
	return file_entity_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *EntityMetadata) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

func (x *EntityMetadata) GetModifiedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedOn
	}
	return nil
}

func (x *EntityMetadata) GetDeletedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedOn
	}
	return nil
}

func (x *EntityMetadata) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

func (x *EntityMetadata) GetReplicable() bool {
	if x != nil {
		return x.Replicable
	}
	return false
}

func (x *EntityMetadata) GetImmutable() bool {
	if x != nil {
		return x.Immutable
	}
	return false
}

func (x *EntityMetadata) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *EntityMetadata) GetSynthetic() bool {
	if x != nil {
		return x.Synthetic
	}
	return false
}

func (x *EntityMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EntityMetadata) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_entity_metadata_proto protoreflect.FileDescriptor

const file_entity_metadata_proto_rawDesc = "" +
	"\n" +
	"\x15entity_metadata.proto\x12\x0esixafter.types\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\rversion.proto\"\xbd\x03\n" +
	"\x0eEntityMetadata\x129\n" +
	"\n" +
	"created_on\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedOn\x12;\n" +
	"\vmodified_on\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedOn\x129\n" +
	"\n" +
	"deleted_on\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedOn\x12\x1c\n" +
	"\tephemeral\x18\x04 \x01(\bR\tephemeral\x12\x1e\n" +
	"\n" +
	"replicable\x18\x05 \x01(\bR\n" +
	"replicable\x12\x1c\n" +
	"\timmutable\x18\x06 \x01(\bR\timmutable\x121\n" +
	"\aversion\x18\a \x01(\v2\x17.sixafter.types.VersionR\aversion\x12\x1c\n" +
	"\tsynthetic\x18\b \x01(\bR\tsynthetic\x12\x12\n" +
	"\x04tags\x18\t \x03(\tR\x04tags\x127\n" +
	"\n" +
	"attributes\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributesBu\n" +
	"\x12com.sixafter.typesB\x13EntityMetadataProtoP\x01Z\x1fgithub.com/sixafter/types;types\xf8\x01\x01\xa2\x02\x03TPB\xaa\x02\x1dSixAfter.Types.WellKnownTypesb\x06proto3"

var (
	file_entity_metadata_proto_rawDescOnce sync.Once
	file_entity_metadata_proto_rawDescData []byte
)

func file_entity_metadata_proto_rawDescGZIP() []byte {
	file_entity_metadata_proto_rawDescOnce.Do(func() {
		file_entity_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entity_metadata_proto_rawDesc), len(file_entity_metadata_proto_rawDesc)))
	})
	return file_entity_metadata_proto_rawDescData
}

var file_entity_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entity_metadata_proto_goTypes = []any{
	(*EntityMetadata)(nil),        // 0: sixafter.types.EntityMetadata
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*Version)(nil),               // 2: sixafter.types.Version
	(*structpb.Struct)(nil),       // 3: google.protobuf.Struct
}
var file_entity_metadata_proto_depIdxs = []int32{
	1, // 0: sixafter.types.EntityMetadata.created_on:type_name -> google.protobuf.Timestamp
	1, // 1: sixafter.types.EntityMetadata.modified_on:type_name -> google.protobuf.Timestamp
	1, // 2: sixafter.types.EntityMetadata.deleted_on:type_name -> google.protobuf.Timestamp
	2, // 3: sixafter.types.EntityMetadata.version:type_name -> sixafter.types.Version
	3, // 4: sixafter.types.EntityMetadata.attributes:type_name -> google.protobuf.Struct
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_entity_metadata_proto_init() }
func file_entity_metadata_proto_init() {
	if File_entity_metadata_proto != nil {
		return
	}
	file_version_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entity_metadata_proto_rawDesc), len(file_entity_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entity_metadata_proto_goTypes,
		DependencyIndexes: file_entity_metadata_proto_depIdxs,
		MessageInfos:      file_entity_metadata_proto_msgTypes,
	}.Build()
	File_entity_metadata_proto = out.File
	file_entity_metadata_proto_goTypes = nil
	file_entity_metadata_proto_depIdxs = nil
}
