// Copyright 2020-2025 SIX AFTER, INC (SIX AFTER)
//
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: SIX AFTER, INC (SIX AFTER)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: geospatial_location.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The `GeospatialLocation` message represents a spatial or temporal scale,
// combining geographical coordinates, heading, movement, and timestamp.
// It is commonly used in location-based services, navigation systems, and
// applications requiring geospatial data.
type GeospatialLocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The geographical coordinate information of the location.
	// Includes latitude, longitude, and elevation as defined in the `GeospatialCoordinate` message.
	Coordinate *GeospatialCoordinate `protobuf:"bytes,1,opt,name=coordinate,proto3" json:"coordinate,omitempty"`
	// The azimuth (orientation) of the device relative to true or magnetic north.
	// Defined using the `CompassHeading` message, it represents the heading
	// of the device at the time of measurement.
	Heading *CompassHeading `protobuf:"bytes,2,opt,name=heading,proto3" json:"heading,omitempty"`
	// The direction in which the device is traveling, measured in degrees
	// relative to true north (0°). This reflects the course or trajectory
	// of the device's movement.
	//
	// **Note:** Course direction is different from heading. Course measures
	// the direction the device is moving (e.g., forward travel), independent
	// of its physical orientation. Heading reflects the device's orientation.
	// Example: 90° indicates the device is moving east.
	Course float64 `protobuf:"fixed64,3,opt,name=course,proto3" json:"course,omitempty"`
	// The instantaneous speed of the device, measured in meters per second (m/s).
	// Example: A speed of 3.5 m/s (12.6 km/h or 7.8 mph) indicates the device
	// is moving at a walking pace.
	Speed float32 `protobuf:"fixed32,4,opt,name=speed,proto3" json:"speed,omitempty"`
	// The time at which this geospatial location data was recorded.
	// Example: Timestamp of "2024-11-17T15:00:00Z" represents 3:00 PM UTC on November 17, 2024.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeospatialLocation) Reset() {
	*x = GeospatialLocation{}
	mi := &file_geospatial_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeospatialLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeospatialLocation) ProtoMessage() {}

func (x *GeospatialLocation) ProtoReflect() protoreflect.Message {
	mi := &file_geospatial_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeospatialLocation.ProtoReflect.Descriptor instead.
func (*GeospatialLocation) Descriptor() ([]byte, []int) {
	return file_geospatial_location_proto_rawDescGZIP(), []int{0}
}

func (x *GeospatialLocation) GetCoordinate() *GeospatialCoordinate {
	if x != nil {
		return x.Coordinate
	}
	return nil
}

func (x *GeospatialLocation) GetHeading() *CompassHeading {
	if x != nil {
		return x.Heading
	}
	return nil
}

func (x *GeospatialLocation) GetCourse() float64 {
	if x != nil {
		return x.Course
	}
	return 0
}

func (x *GeospatialLocation) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *GeospatialLocation) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_geospatial_location_proto protoreflect.FileDescriptor

const file_geospatial_location_proto_rawDesc = "" +
	"\n" +
	"\x19geospatial_location.proto\x12\x0esixafter.types\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15compass_heading.proto\x1a\x1bgeospatial_coordinate.proto\"\xfc\x01\n" +
	"\x12GeospatialLocation\x12D\n" +
	"\n" +
	"coordinate\x18\x01 \x01(\v2$.sixafter.types.GeospatialCoordinateR\n" +
	"coordinate\x128\n" +
	"\aheading\x18\x02 \x01(\v2\x1e.sixafter.types.CompassHeadingR\aheading\x12\x16\n" +
	"\x06course\x18\x03 \x01(\x01R\x06course\x12\x14\n" +
	"\x05speed\x18\x04 \x01(\x02R\x05speed\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampBy\n" +
	"\x12com.sixafter.typesB\x17GeospatialLocationProtoP\x01Z\x1fgithub.com/sixafter/types;types\xf8\x01\x01\xa2\x02\x03TPB\xaa\x02\x1dSixAfter.Types.WellKnownTypesb\x06proto3"

var (
	file_geospatial_location_proto_rawDescOnce sync.Once
	file_geospatial_location_proto_rawDescData []byte
)

func file_geospatial_location_proto_rawDescGZIP() []byte {
	file_geospatial_location_proto_rawDescOnce.Do(func() {
		file_geospatial_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_geospatial_location_proto_rawDesc), len(file_geospatial_location_proto_rawDesc)))
	})
	return file_geospatial_location_proto_rawDescData
}

var file_geospatial_location_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_geospatial_location_proto_goTypes = []any{
	(*GeospatialLocation)(nil),    // 0: sixafter.types.GeospatialLocation
	(*GeospatialCoordinate)(nil),  // 1: sixafter.types.GeospatialCoordinate
	(*CompassHeading)(nil),        // 2: sixafter.types.CompassHeading
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_geospatial_location_proto_depIdxs = []int32{
	1, // 0: sixafter.types.GeospatialLocation.coordinate:type_name -> sixafter.types.GeospatialCoordinate
	2, // 1: sixafter.types.GeospatialLocation.heading:type_name -> sixafter.types.CompassHeading
	3, // 2: sixafter.types.GeospatialLocation.timestamp:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_geospatial_location_proto_init() }
func file_geospatial_location_proto_init() {
	if File_geospatial_location_proto != nil {
		return
	}
	file_compass_heading_proto_init()
	file_geospatial_coordinate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_geospatial_location_proto_rawDesc), len(file_geospatial_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_geospatial_location_proto_goTypes,
		DependencyIndexes: file_geospatial_location_proto_depIdxs,
		MessageInfos:      file_geospatial_location_proto_msgTypes,
	}.Build()
	File_geospatial_location_proto = out.File
	file_geospatial_location_proto_goTypes = nil
	file_geospatial_location_proto_depIdxs = nil
}
