// Copyright 2026 SIX AFTER, INC (SIX AFTER)
//
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: SIX AFTER, INC (SIX AFTER)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: proto/v1/time_zone.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The `TimeZone` message represents a time zone, which is an area
// observing a uniform standard time for legal, commercial, and social purposes.
//
// `name` identifies the zone. `utc_offset`, `abbreviation`, and `daylight_saving`
// describe the zone as it was in effect at a specific instant, normally the
// timestamp of the record that contains this message. To compute the offset for
// any other instant, look up `name` in the IANA Time Zone Database.
type TimeZone struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The IANA Time Zone Database identifier of the time zone.
	// Example: "America/New_York".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The abbreviation in effect.
	// Abbreviations are for display only: they are not unique ("CST" is used in the
	// United States, China, and Cuba) and may be numeric (e.g., "-03").
	// Example: "EDT" for "America/New_York" during daylight saving time.
	Abbreviation string `protobuf:"bytes,2,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	// The offset from UTC in effect.
	// The offset is positive east of UTC and negative west of UTC, and its sign applies
	// to the whole value, as in ISO 8601.
	// Example: -14400s (UTC-04:00) for "America/New_York" during daylight saving time;
	// -12600s (UTC-03:30) for "America/St_Johns" during standard time; 19800s
	// (UTC+05:30) for "Asia/Kolkata".
	// Unset means the offset is unknown; a set offset of 0 is UTC.
	UtcOffset *durationpb.Duration `protobuf:"bytes,3,opt,name=utc_offset,json=utcOffset,proto3" json:"utc_offset,omitempty"`
	// True if daylight saving time is in effect.
	DaylightSaving bool `protobuf:"varint,4,opt,name=daylight_saving,json=daylightSaving,proto3" json:"daylight_saving,omitempty"`
	// The location of the time zone's principal city, as listed in the IANA Time Zone
	// Database file zone1970.tab.
	// Example: Manhattan (40.7142, -74.0064) for "America/New_York".
	// This is a representative location, not a geometric center, and it is not
	// sufficient to determine a location's time zone; that requires zone boundaries.
	// Unset means the central coordinate is unknown.
	CentralCoordinate *GeospatialCoordinate `protobuf:"bytes,5,opt,name=central_coordinate,json=centralCoordinate,proto3" json:"central_coordinate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TimeZone) Reset() {
	*x = TimeZone{}
	mi := &file_proto_v1_time_zone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeZone) ProtoMessage() {}

func (x *TimeZone) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_time_zone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeZone.ProtoReflect.Descriptor instead.
func (*TimeZone) Descriptor() ([]byte, []int) {
	return file_proto_v1_time_zone_proto_rawDescGZIP(), []int{0}
}

func (x *TimeZone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TimeZone) GetAbbreviation() string {
	if x != nil {
		return x.Abbreviation
	}
	return ""
}

func (x *TimeZone) GetUtcOffset() *durationpb.Duration {
	if x != nil {
		return x.UtcOffset
	}
	return nil
}

func (x *TimeZone) GetDaylightSaving() bool {
	if x != nil {
		return x.DaylightSaving
	}
	return false
}

func (x *TimeZone) GetCentralCoordinate() *GeospatialCoordinate {
	if x != nil {
		return x.CentralCoordinate
	}
	return nil
}

var File_proto_v1_time_zone_proto protoreflect.FileDescriptor

const file_proto_v1_time_zone_proto_rawDesc = "" +
	"\n" +
	"\x18proto/v1/time_zone.proto\x12\x17sixafter.types.proto.v1\x1a\x1egoogle/protobuf/duration.proto\x1a$proto/v1/geospatial_coordinate.proto\"\x83\x02\n" +
	"\bTimeZone\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\fabbreviation\x18\x02 \x01(\tR\fabbreviation\x128\n" +
	"\n" +
	"utc_offset\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\tutcOffset\x12'\n" +
	"\x0fdaylight_saving\x18\x04 \x01(\bR\x0edaylightSaving\x12\\\n" +
	"\x12central_coordinate\x18\x05 \x01(\v2-.sixafter.types.proto.v1.GeospatialCoordinateR\x11centralCoordinateBo\n" +
	"\x15com.sixafter.types.v1B\rTimeZoneProtoP\x01Z+github.com/sixafter/types/proto/v1/pb;types\xa2\x02\x03TPB\xaa\x02\x11SixAfter.Types.V1b\x06proto3"

var (
	file_proto_v1_time_zone_proto_rawDescOnce sync.Once
	file_proto_v1_time_zone_proto_rawDescData []byte
)

func file_proto_v1_time_zone_proto_rawDescGZIP() []byte {
	file_proto_v1_time_zone_proto_rawDescOnce.Do(func() {
		file_proto_v1_time_zone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_time_zone_proto_rawDesc), len(file_proto_v1_time_zone_proto_rawDesc)))
	})
	return file_proto_v1_time_zone_proto_rawDescData
}

var file_proto_v1_time_zone_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_v1_time_zone_proto_goTypes = []any{
	(*TimeZone)(nil),             // 0: sixafter.types.proto.v1.TimeZone
	(*durationpb.Duration)(nil),  // 1: google.protobuf.Duration
	(*GeospatialCoordinate)(nil), // 2: sixafter.types.proto.v1.GeospatialCoordinate
}
var file_proto_v1_time_zone_proto_depIdxs = []int32{
	1, // 0: sixafter.types.proto.v1.TimeZone.utc_offset:type_name -> google.protobuf.Duration
	2, // 1: sixafter.types.proto.v1.TimeZone.central_coordinate:type_name -> sixafter.types.proto.v1.GeospatialCoordinate
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_v1_time_zone_proto_init() }
func file_proto_v1_time_zone_proto_init() {
	if File_proto_v1_time_zone_proto != nil {
		return
	}
	file_proto_v1_geospatial_coordinate_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_time_zone_proto_rawDesc), len(file_proto_v1_time_zone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_v1_time_zone_proto_goTypes,
		DependencyIndexes: file_proto_v1_time_zone_proto_depIdxs,
		MessageInfos:      file_proto_v1_time_zone_proto_msgTypes,
	}.Build()
	File_proto_v1_time_zone_proto = out.File
	file_proto_v1_time_zone_proto_goTypes = nil
	file_proto_v1_time_zone_proto_depIdxs = nil
}
