// Copyright 2020-2025 SIX AFTER, INC (SIX AFTER)
//
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: SIX AFTER, INC (SIX AFTER)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: sixafter/types/email_address.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The `EmailAddress` message represents an electronic mail (email) address
// as defined by RFC 5322. It separates the email address into its two main
// components: the local part and the domain part.
type EmailAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The local part of the email address.
	// This is the portion of the address before the "@" symbol.
	// Example: "john.doe" in the email address "john.doe@example.com".
	LocalPart string `protobuf:"bytes,1,opt,name=local_part,json=localPart,proto3" json:"local_part,omitempty"`
	// The domain part of the email address.
	// This is the portion of the address after the "@" symbol.
	// It identifies the mail server responsible for accepting emails for the address.
	// Example: "example.com" in the email address "john.doe@example.com".
	DomainPart    string `protobuf:"bytes,2,opt,name=domain_part,json=domainPart,proto3" json:"domain_part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailAddress) Reset() {
	*x = EmailAddress{}
	mi := &file_sixafter_types_email_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAddress) ProtoMessage() {}

func (x *EmailAddress) ProtoReflect() protoreflect.Message {
	mi := &file_sixafter_types_email_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailAddress.ProtoReflect.Descriptor instead.
func (*EmailAddress) Descriptor() ([]byte, []int) {
	return file_sixafter_types_email_address_proto_rawDescGZIP(), []int{0}
}

func (x *EmailAddress) GetLocalPart() string {
	if x != nil {
		return x.LocalPart
	}
	return ""
}

func (x *EmailAddress) GetDomainPart() string {
	if x != nil {
		return x.DomainPart
	}
	return ""
}

var File_sixafter_types_email_address_proto protoreflect.FileDescriptor

const file_sixafter_types_email_address_proto_rawDesc = "" +
	"\n" +
	"\"sixafter/types/email_address.proto\x12\x0esixafter.types\"N\n" +
	"\fEmailAddress\x12\x1d\n" +
	"\n" +
	"local_part\x18\x01 \x01(\tR\tlocalPart\x12\x1f\n" +
	"\vdomain_part\x18\x02 \x01(\tR\n" +
	"domainPartBs\n" +
	"\x12com.sixafter.typesB\x11EmailAddressProtoP\x01Z\x1fgithub.com/sixafter/types;types\xf8\x01\x01\xa2\x02\x03TPB\xaa\x02\x1dSixAfter.Types.WellKnownTypesb\x06proto3"

var (
	file_sixafter_types_email_address_proto_rawDescOnce sync.Once
	file_sixafter_types_email_address_proto_rawDescData []byte
)

func file_sixafter_types_email_address_proto_rawDescGZIP() []byte {
	file_sixafter_types_email_address_proto_rawDescOnce.Do(func() {
		file_sixafter_types_email_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sixafter_types_email_address_proto_rawDesc), len(file_sixafter_types_email_address_proto_rawDesc)))
	})
	return file_sixafter_types_email_address_proto_rawDescData
}

var file_sixafter_types_email_address_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sixafter_types_email_address_proto_goTypes = []any{
	(*EmailAddress)(nil), // 0: sixafter.types.EmailAddress
}
var file_sixafter_types_email_address_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sixafter_types_email_address_proto_init() }
func file_sixafter_types_email_address_proto_init() {
	if File_sixafter_types_email_address_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sixafter_types_email_address_proto_rawDesc), len(file_sixafter_types_email_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sixafter_types_email_address_proto_goTypes,
		DependencyIndexes: file_sixafter_types_email_address_proto_depIdxs,
		MessageInfos:      file_sixafter_types_email_address_proto_msgTypes,
	}.Build()
	File_sixafter_types_email_address_proto = out.File
	file_sixafter_types_email_address_proto_goTypes = nil
	file_sixafter_types_email_address_proto_depIdxs = nil
}
