// Copyright 2026 SIX AFTER, INC (SIX AFTER)
//
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: SIX AFTER, INC (SIX AFTER)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package sixafter.types.proto.v1;

option csharp_namespace = "SixAfter.Types.V1";
option go_package = "github.com/sixafter/types/proto/v1/pb;types";
option java_multiple_files = true;
option java_outer_classname = "UriProto";
option java_package = "com.sixafter.types.v1";
option objc_class_prefix = "TPB";

// The `Uri` message represents a Uniform Resource Identifier (URI) as defined by
// [RFC 3986: Uniform Resource Identifier (URI): Generic Syntax](https://www.rfc-editor.org/rfc/rfc3986).
// A URI is a compact string used to identify a resource in a generic syntax.
message Uri {
  // The scheme component of the URI.
  // Example: "https", "ftp", or "mailto".
  string scheme = 1;

  // The fragment component of the URI.
  // This is the optional part of the URI that follows a "#" and provides an identifier
  // to a secondary resource.
  // Example: "section1" in "https://example.com/page#section1".
  string fragment = 2;

  // The host component of the URI.
  // This identifies the domain name or IP address of the resource.
  // Example: "example.com" or "192.168.1.1".
  string host = 3;

  // The port number of the URI.
  // This is the optional number that specifies the communication port.
  // Valid values are 1 through 65535. A value of 0 means no port was given,
  // and the default port for the scheme applies.
  // Example: 443 for HTTPS.
  uint32 port = 4;

  // The query component of the URI.
  // This contains optional parameters appended to the URI, following a "?".
  // Example: "id=123&name=test" in "https://example.com/page?id=123&name=test".
  string query = 5;

  // The user-information component of the URI.
  // This is the optional part before the host that provides user credentials.
  // Example: "user:password" in "https://user:password@example.com".
  string user_info = 6;

  // The path component of the URI.
  // This is the hierarchical part that follows the authority and precedes the
  // optional query ("?") and fragment ("#") components. It may be empty.
  // Example: "/a/b" in "https://example.com/a/b?x=1#f".
  string path = 7;
}
